### ISSUE TITLE
help for results!

### ISSUE THREAD

**Issue by xiangwei6963** [zaihebian/OXIS-oxidative-stress-predictor#1]
Hi authors:
     I got a different result with yours in the article when I run it for TCGA-THCA. So what could I do?
      Thank you for the help!
![THCA](https://user-images.githubusercontent.com/58254194/175848790-cddc76c4-a134-45fd-8aec-bd0e761c6e17.jpg)

**Comment by zaihebian** [comment]
I'm not sure why that happens. I suggest to check the sample information, especially the sample types. What's more, the data we used is downloaded by recount3, which means the data has be normalized in some way to make it comparable to the data from GTEx, so it might be not exactly the same with the data directly downloaded from TCGA.
